// svgpng.ts — PNG encoder kernel for the `svgpng` block.
//
// Generated by the `wasmsmith` skill. The block rasterizes an SVG to RGBA pixels
// with the browser canvas (native — NOT a WASM candidate), then this kernel does
// the genuinely compute-bound part: turn those pixels into compressed PNG bytes.
//
// Pipeline (all in one `encode` call, one pass over the image):
//   1. PNG "Up" scanline filter (each byte minus the byte above) — turns flat
//      regions into runs of zeros that compress well.
//   2. Adler-32 over the filtered bytes (the zlib checksum).
//   3. DEFLATE the filtered bytes: fixed-Huffman block + greedy LZ77 with a
//      hash-chain matcher (the hot loop — this is where WASM beats JS).
// Output is a raw zlib stream (2-byte header + DEFLATE body + 4-byte Adler-32),
// i.e. exactly the PNG IDAT payload. The host wraps it in PNG chunks (trivial).
//
// Compiled with `--runtime stub`: no GC, explicit linear memory via a bump
// allocator; the host marshals typed arrays in/out. See svgpng.manifest.json.

// ── bump allocator (identical shape to the golden fuzzysearch kernel) ─────────
let bumpPtr: i32 = 1024;

export function reset(): void {
  bumpPtr = 1024;
}

export function alloc(byteLen: i32): i32 {
  const ptr = (bumpPtr + 7) & ~7;
  bumpPtr = ptr + byteLen;
  const needPages = ((bumpPtr + 0xffff) & ~0xffff) >>> 16;
  const havePages = memory.size();
  if (needPages > havePages) memory.grow(needPages - havePages);
  return ptr;
}

// ── DEFLATE constants ────────────────────────────────────────────────────────
const MIN_MATCH: i32 = 3;
const MAX_MATCH: i32 = 258;
const WSIZE: i32 = 32768;
const WMASK: i32 = 32767;
const HMASK: i32 = 32767; // 15-bit hash
const MAX_CHAIN: i32 = 128; // hash-chain search depth (ratio vs speed)

// ── bit-packed output state (module globals, reset each encode) ───────────────
let outHead: i32 = 0; // byte ptr where DEFLATE bytes begin (out + 2)
let outPos: i32 = 0; // bytes written so far
let bitBuf: u32 = 0;
let bitCnt: i32 = 0;
let fp0: i32 = 0; // filtered-buffer byte ptr
let flen: i32 = 0; // filtered-buffer length

// Append the low `count` bits of `value`, LSB-first, flushing whole bytes.
@inline
function sendBits(value: i32, count: i32): void {
  bitBuf |= (<u32>value) << bitCnt;
  bitCnt += count;
  while (bitCnt >= 8) {
    store<u8>(outHead + outPos, <u8>(bitBuf & 0xff));
    outPos += 1;
    bitBuf >>= 8;
    bitCnt -= 8;
  }
}

// DEFLATE stores Huffman codes MSB-first; our bit buffer is LSB-first, so send
// the bit-reversed code.
@inline
function sendCode(code: i32, len: i32): void {
  let r = 0;
  let c = code;
  for (let i = 0; i < len; i += 1) {
    r = (r << 1) | (c & 1);
    c >>= 1;
  }
  sendBits(r, len);
}

// Fixed-Huffman literal / length symbol (0..285).
@inline
function sendLitLen(sym: i32): void {
  if (sym <= 143) sendCode(0x30 + sym, 8);
  else if (sym <= 255) sendCode(0x190 + (sym - 144), 9);
  else if (sym <= 279) sendCode(sym - 256, 7);
  else sendCode(0xc0 + (sym - 280), 8);
}

// Emit a back-reference: length (3..258) + distance (1..32768).
function sendMatch(len: i32, dist: i32): void {
  // length symbol + extra bits
  if (len <= 10) {
    sendLitLen(254 + len); // 3->257 .. 10->264
  } else if (len == 258) {
    sendLitLen(285);
  } else {
    let sym: i32; let eb: i32; let base: i32;
    if (len <= 18) { eb = 1; sym = 265 + ((len - 11) >> 1); base = 11 + ((len - 11) & ~1); }
    else if (len <= 34) { eb = 2; sym = 269 + ((len - 19) >> 2); base = 19 + ((len - 19) & ~3); }
    else if (len <= 66) { eb = 3; sym = 273 + ((len - 35) >> 3); base = 35 + ((len - 35) & ~7); }
    else if (len <= 130) { eb = 4; sym = 277 + ((len - 67) >> 4); base = 67 + ((len - 67) & ~15); }
    else { eb = 5; sym = 281 + ((len - 131) >> 5); base = 131 + ((len - 131) & ~31); }
    sendLitLen(sym);
    sendBits(len - base, eb);
  }
  // distance symbol (5-bit fixed code) + extra bits
  if (dist <= 4) {
    sendCode(dist - 1, 5);
  } else {
    let sym: i32; let eb: i32; let base: i32;
    if (dist <= 8) { eb = 1; sym = 4 + ((dist - 5) >> 1); base = 5 + ((dist - 5) & ~1); }
    else if (dist <= 16) { eb = 2; sym = 6 + ((dist - 9) >> 2); base = 9 + ((dist - 9) & ~3); }
    else if (dist <= 32) { eb = 3; sym = 8 + ((dist - 17) >> 3); base = 17 + ((dist - 17) & ~7); }
    else if (dist <= 64) { eb = 4; sym = 10 + ((dist - 33) >> 4); base = 33 + ((dist - 33) & ~15); }
    else if (dist <= 128) { eb = 5; sym = 12 + ((dist - 65) >> 5); base = 65 + ((dist - 65) & ~31); }
    else if (dist <= 256) { eb = 6; sym = 14 + ((dist - 129) >> 6); base = 129 + ((dist - 129) & ~63); }
    else if (dist <= 512) { eb = 7; sym = 16 + ((dist - 257) >> 7); base = 257 + ((dist - 257) & ~127); }
    else if (dist <= 1024) { eb = 8; sym = 18 + ((dist - 513) >> 8); base = 513 + ((dist - 513) & ~255); }
    else if (dist <= 2048) { eb = 9; sym = 20 + ((dist - 1025) >> 9); base = 1025 + ((dist - 1025) & ~511); }
    else if (dist <= 4096) { eb = 10; sym = 22 + ((dist - 2049) >> 10); base = 2049 + ((dist - 2049) & ~1023); }
    else if (dist <= 8192) { eb = 11; sym = 24 + ((dist - 4097) >> 11); base = 4097 + ((dist - 4097) & ~2047); }
    else if (dist <= 16384) { eb = 12; sym = 26 + ((dist - 8193) >> 12); base = 8193 + ((dist - 8193) & ~4095); }
    else { eb = 13; sym = 28 + ((dist - 16385) >> 13); base = 16385 + ((dist - 16385) & ~8191); }
    sendCode(sym, 5);
    sendBits(dist - base, eb);
  }
}

@inline
function hash3(p: i32): i32 {
  const b0 = <i32>load<u8>(fp0 + p);
  const b1 = <i32>load<u8>(fp0 + p + 1);
  const b2 = <i32>load<u8>(fp0 + p + 2);
  return ((b0 << 10) ^ (b1 << 5) ^ b2) & HMASK;
}

// Encode an RGBA image to a zlib stream (PNG IDAT payload).
//   pixelsPtr : u8[height * width * 4]   input, row-major RGBA (in)
//   filtered  : u8[height * (1 + width*4)]  scratch for the filtered stream
//   head      : i32[32768]  hash heads (scratch, cleared here)
//   prev      : i32[32768]  hash chains (scratch)
//   out       : bytes for the zlib stream (out); caller sizes it generously
// returns the zlib stream length in bytes.
export function encode(
  pixelsPtr: i32,
  width: i32,
  height: i32,
  filteredPtr: i32,
  headPtr: i32,
  prevPtr: i32,
  outPtr: i32,
): i32 {
  const stride = width * 4;

  // 1. "Up" filter into the filtered buffer, tracking Adler-32 as we go.
  let fp = 0;
  for (let r = 0; r < height; r += 1) {
    store<u8>(filteredPtr + fp, 2); // filter type: Up
    fp += 1;
    const rowPtr = pixelsPtr + r * stride;
    const abovePtr = rowPtr - stride;
    if (r == 0) {
      for (let i = 0; i < stride; i += 1) {
        store<u8>(filteredPtr + fp, load<u8>(rowPtr + i));
        fp += 1;
      }
    } else {
      for (let i = 0; i < stride; i += 1) {
        const v = (<i32>load<u8>(rowPtr + i)) - (<i32>load<u8>(abovePtr + i));
        store<u8>(filteredPtr + fp, <u8>(v & 0xff));
        fp += 1;
      }
    }
  }
  fp0 = filteredPtr;
  flen = fp;

  // 2. Adler-32 of the filtered bytes (batched to defer the modulo).
  let a: u32 = 1;
  let b: u32 = 0;
  let i = 0;
  while (i < flen) {
    let n = flen - i;
    if (n > 5552) n = 5552;
    for (let k = 0; k < n; k += 1) {
      a += <u32>load<u8>(filteredPtr + i + k);
      b += a;
    }
    a %= 65521;
    b %= 65521;
    i += n;
  }
  const adler = (b << 16) | a;

  // 3. DEFLATE (fixed Huffman + greedy LZ77) into out, after a 2-byte zlib head.
  store<u8>(outPtr, 0x78); // CMF
  store<u8>(outPtr + 1, 0x01); // FLG (0x7801 % 31 == 0)
  outHead = outPtr + 2;
  outPos = 0;
  bitBuf = 0;
  bitCnt = 0;

  // clear hash heads
  for (let h = 0; h < 32768; h += 1) store<i32>(headPtr + (h << 2), -1);

  sendBits(1, 1); // BFINAL = 1
  sendBits(1, 2); // BTYPE  = 01 (fixed Huffman)

  let pos = 0;
  while (pos < flen) {
    let bestLen = MIN_MATCH - 1;
    let bestDist = 0;

    if (pos + MIN_MATCH <= flen) {
      let maxLen = flen - pos;
      if (maxLen > MAX_MATCH) maxLen = MAX_MATCH;
      const h = hash3(pos);
      let cand = load<i32>(headPtr + (h << 2));
      let chain = MAX_CHAIN;
      while (cand >= 0 && (pos - cand) <= WSIZE && chain > 0) {
        if (load<u8>(fp0 + cand + bestLen) == load<u8>(fp0 + pos + bestLen)) {
          let len = 0;
          while (len < maxLen && load<u8>(fp0 + cand + len) == load<u8>(fp0 + pos + len)) len += 1;
          if (len > bestLen) {
            bestLen = len;
            bestDist = pos - cand;
            if (len >= maxLen) break;
          }
        }
        cand = load<i32>(prevPtr + ((cand & WMASK) << 2));
        chain -= 1;
      }
    }

    if (bestLen >= MIN_MATCH) {
      sendMatch(bestLen, bestDist);
      const end = pos + bestLen;
      while (pos < end) {
        if (pos + MIN_MATCH <= flen) {
          const hh = hash3(pos);
          store<i32>(prevPtr + ((pos & WMASK) << 2), load<i32>(headPtr + (hh << 2)));
          store<i32>(headPtr + (hh << 2), pos);
        }
        pos += 1;
      }
    } else {
      sendLitLen(<i32>load<u8>(filteredPtr + pos));
      if (pos + MIN_MATCH <= flen) {
        const hh = hash3(pos);
        store<i32>(prevPtr + ((pos & WMASK) << 2), load<i32>(headPtr + (hh << 2)));
        store<i32>(headPtr + (hh << 2), pos);
      }
      pos += 1;
    }
  }

  sendLitLen(256); // end-of-block
  if (bitCnt > 0) { // flush partial byte
    store<u8>(outHead + outPos, <u8>(bitBuf & 0xff));
    outPos += 1;
    bitBuf = 0;
    bitCnt = 0;
  }

  // 4. Append Adler-32 (big-endian) after the DEFLATE bytes.
  const tail = outPtr + 2 + outPos;
  store<u8>(tail, <u8>((adler >>> 24) & 0xff));
  store<u8>(tail + 1, <u8>((adler >>> 16) & 0xff));
  store<u8>(tail + 2, <u8>((adler >>> 8) & 0xff));
  store<u8>(tail + 3, <u8>(adler & 0xff));

  return 2 + outPos + 4;
}
